#!/bin/bash
# /usr/local/sbin/temperature

CORETEMP="/sys/devices/platform/coretemp.0/hwmon/hwmon1"
APPLE="/sys/devices/platform/applesmc.768"

x=$(cat $CORETEMP/temp2_input)
x=$((x/1000))

if [ $x -gt 90 ]
then
    echo 1800 | tee $APPLE/fan3_min > /dev/null
elif [ $x -gt 80 ]
then
    echo 1500 | tee $APPLE/fan3_min > /dev/null
elif [ $x -gt 70 ]
then
    echo 1250 | tee $APPLE/fan3_min > /dev/null
elif [ $x -gt 60 ]
then
    echo 1000 | tee $APPLE/fan3_min > /dev/null
elif [ $x -gt 50 ]
then
    echo 800 | tee $APPLE/fan3_min > /dev/null
else
    echo 600 | tee $APPLE/fan3_min > /dev/null
